In [27]:
import pandas as pd
import quandl
import math
import numpy as np
from sklearn import preprocessing, cross_validation, svm
from sklearn.linear_model import LinearRegression 

df = quandl.get('WIKI/GOOGL')

In [28]:
df

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2004-08-19,100.010,104.06,95.960,100.335,44659000.0,0.0,1.0,50.159839,52.191109,48.128568,50.322842,44659000.0
2004-08-20,101.010,109.08,100.500,108.310,22834300.0,0.0,1.0,50.661387,54.708881,50.405597,54.322689,22834300.0
2004-08-23,110.760,113.48,109.050,109.400,18256100.0,0.0,1.0,55.551482,56.915693,54.693835,54.869377,18256100.0
2004-08-24,111.240,111.60,103.570,104.870,15247300.0,0.0,1.0,55.792225,55.972783,51.945350,52.597363,15247300.0
2004-08-25,104.760,108.00,103.880,106.000,9188600.0,0.0,1.0,52.542193,54.167209,52.100830,53.164113,9188600.0
2004-08-26,104.950,107.95,104.660,107.910,7094800.0,0.0,1.0,52.637487,54.142132,52.492038,54.122070,7094800.0
2004-08-27,108.100,108.62,105.690,106.150,6211700.0,0.0,1.0,54.217364,54.478169,53.008633,53.239345,6211700.0
2004-08-30,105.280,105.49,102.010,102.010,5196700.0,0.0,1.0,52.802998,52.908323,51.162935,51.162935,5196700.0
2004-08-31,102.320,103.71,102.160,102.370,4917800.0,0.0,1.0,51.318415,52.015567,51.238167,51.343492,4917800.0
2004-09-01,102.700,102.97,99.670,100.250,9138200.0,0.0,1.0,51.509003,51.644421,49.989312,50.280210,9138200.0
2004-09-02,99.090,102.37,98.940,101.510,15118600.0,0.0,1.0,49.698414,51.343492,49.623182,50.912161,15118600.0
2004-09-03,100.950,101.74,99.320,100.010,5152400.0,0.0,1.0,50.631294,51.027517,49.813770,50.159839,5152400.0
2004-09-07,101.010,102.00,99.610,101.580,5847500.0,0.0,1.0,50.661387,51.157920,49.959219,50.947269,5847500.0
2004-09-08,100.740,103.03,100.500,102.300,4985600.0,0.0,1.0,50.525969,51.674514,50.405597,51.308384,4985600.0
2004-09-09,102.500,102.71,101.000,102.310,4061700.0,0.0,1.0,51.408694,51.514019,50.656371,51.313400,4061700.0
2004-09-10,101.470,106.56,101.300,105.330,8698800.0,0.0,1.0,50.892099,53.444980,50.806836,52.828075,8698800.0
2004-09-13,106.630,108.41,106.460,107.500,7844100.0,0.0,1.0,53.480088,54.372844,53.394825,53.916435,7844100.0
2004-09-14,107.440,112.00,106.790,111.490,10828900.0,0.0,1.0,53.886342,56.173402,53.560336,55.917612,10828900.0
2004-09-15,110.560,114.23,110.200,112.000,10713000.0,0.0,1.0,55.451172,57.291854,55.270615,56.173402,10713000.0
2004-09-16,112.340,115.80,111.650,113.970,9266300.0,0.0,1.0,56.343928,58.079285,55.997860,57.161452,9266300.0
2004-09-17,114.420,117.49,113.550,117.490,9472500.0,0.0,1.0,57.387149,58.926902,56.950802,58.926902,9472500.0
2004-09-20,116.950,121.60,116.770,119.360,10628700.0,0.0,1.0,58.656066,60.988265,58.565787,59.864797,10628700.0
2004-09-21,120.200,120.42,117.510,117.840,7228700.0,0.0,1.0,60.286097,60.396438,58.936933,59.102444,7228700.0
2004-09-22,117.450,119.67,116.810,118.380,7581200.0,0.0,1.0,58.906840,60.020277,58.585849,59.373280,7581200.0
2004-09-23,118.840,122.63,117.020,120.820,8535600.0,0.0,1.0,59.603992,61.504860,58.691174,60.597057,8535600.0
2004-09-24,120.970,124.10,119.760,119.830,9123400.0,0.0,1.0,60.672290,62.242136,60.065416,60.100525,9123400.0
2004-09-27,119.560,120.88,117.800,118.260,7066100.0,0.0,1.0,59.965107,60.627150,59.082382,59.313094,7066100.0
2004-09-28,121.150,127.40,120.210,126.860,16929000.0,0.0,1.0,60.762568,63.897245,60.291113,63.626409,16929000.0
2004-09-29,126.530,135.02,126.230,131.080,30516400.0,0.0,1.0,63.460898,67.719042,63.310433,65.742942,30516400.0
2004-09-30,129.899,132.30,129.000,129.600,13758000.0,0.0,1.0,65.150614,66.354831,64.699722,65.000651,13758000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-06,980.000,994.26,978.510,993.640,1490744.0,0.0,1.0,980.000000,994.260000,978.510000,993.640000,1490744.0
2017-10-09,995.000,1000.46,991.500,992.310,1151035.0,0.0,1.0,995.000000,1000.460000,991.500000,992.310000,1151035.0
2017-10-10,995.300,997.47,981.110,987.800,1158864.0,0.0,1.0,995.300000,997.470000,981.110000,987.800000,1158864.0
2017-10-11,989.040,1007.56,987.940,1005.650,1748443.0,0.0,1.0,989.040000,1007.560000,987.940000,1005.650000,1748443.0
2017-10-12,1003.840,1011.54,1001.100,1005.650,1521137.0,0.0,1.0,1003.840000,1011.540000,1001.100000,1005.650000,1521137.0
2017-10-13,1009.110,1014.76,1007.060,1007.870,1308881.0,0.0,1.0,1009.110000,1014.760000,1007.060000,1007.870000,1308881.0
2017-10-16,1009.630,1012.00,1001.520,1009.350,1066744.0,0.0,1.0,1009.630000,1012.000000,1001.520000,1009.350000,1066744.0
2017-10-17,1007.440,1014.56,1006.050,1011.000,991412.0,0.0,1.0,1007.440000,1014.560000,1006.050000,1011.000000,991412.0
2017-10-18,1011.050,1016.31,1005.320,1012.740,1270218.0,0.0,1.0,1011.050000,1016.310000,1005.320000,1012.740000,1270218.0
2017-10-19,1004.750,1007.32,997.300,1001.840,1677021.0,0.0,1.0,1004.750000,1007.320000,997.300000,1001.840000,1677021.0
2017-10-20,1007.050,1008.65,1002.270,1005.070,1568454.0,0.0,1.0,1007.050000,1008.650000,1002.270000,1005.070000,1568454.0
2017-10-23,1005.180,1005.79,983.100,985.540,1623580.0,0.0,1.0,1005.180000,1005.790000,983.100000,985.540000,1623580.0
2017-10-24,986.500,989.26,977.080,988.490,1416283.0,0.0,1.0,986.500000,989.260000,977.080000,988.490000,1416283.0
2017-10-25,986.270,994.43,977.722,991.460,1368042.0,0.0,1.0,986.270000,994.430000,977.722000,991.460000,1368042.0
2017-10-26,998.470,1006.51,990.470,991.420,1827682.0,0.0,1.0,998.470000,1006.510000,990.470000,991.420000,1827682.0
2017-10-27,1030.990,1063.62,1026.850,1033.670,5139945.0,0.0,1.0,1030.990000,1063.620000,1026.850000,1033.670000,5139945.0
2017-10-30,1029.160,1039.83,1022.330,1033.130,2245352.0,0.0,1.0,1029.160000,1039.830000,1022.330000,1033.130000,2245352.0
2017-10-31,1033.000,1041.00,1026.300,1033.040,1490660.0,0.0,1.0,1033.000000,1041.000000,1026.300000,1033.040000,1490660.0
2017-11-01,1036.320,1047.86,1034.000,1042.600,2105729.0,0.0,1.0,1036.320000,1047.860000,1034.000000,1042.600000,2105729.0
2017-11-02,1039.990,1045.52,1028.660,1042.970,1233333.0,0.0,1.0,1039.990000,1045.520000,1028.660000,1042.970000,1233333.0
2017-11-03,1042.750,1050.66,1037.650,1049.990,1370874.0,0.0,1.0,1042.750000,1050.660000,1037.650000,1049.990000,1370874.0
2017-11-06,1049.100,1052.59,1042.000,1042.680,897897.0,0.0,1.0,1049.100000,1052.590000,1042.000000,1042.680000,897897.0
2017-11-07,1049.650,1053.41,1043.000,1052.390,1254965.0,0.0,1.0,1049.650000,1053.410000,1043.000000,1052.390000,1254965.0
2017-11-09,1048.000,1050.88,1035.850,1047.720,1776722.0,0.0,1.0,1048.000000,1050.880000,1035.850000,1047.720000,1776722.0
2017-11-10,1043.870,1046.63,1041.220,1044.150,955500.0,0.0,1.0,1043.870000,1046.630000,1041.220000,1044.150000,955500.0
2017-11-13,1040.800,1048.74,1039.260,1041.200,914852.0,0.0,1.0,1040.800000,1048.740000,1039.260000,1041.200000,914852.0
2017-11-14,1037.720,1042.30,1029.330,1041.640,982782.0,0.0,1.0,1037.720000,1042.300000,1029.330000,1041.640000,982782.0
2017-11-15,1035.000,1039.63,1030.760,1036.410,900695.0,0.0,1.0,1035.000000,1039.630000,1030.760000,1036.410000,900695.0
2017-11-16,1038.750,1051.76,1038.000,1048.470,1125995.0,0.0,1.0,1038.750000,1051.760000,1038.000000,1048.470000,1125995.0
2017-11-17,1049.800,1051.00,1033.730,1035.890,1286044.0,0.0,1.0,1049.800000,1051.000000,1033.730000,1035.890000,1286044.0

In [29]:
df = df[['Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close', 'Adj. Volume' ] ]

In [30]:
df['HL_PCT'] = (df['Adj. High']-df['Adj. Close'])/ df['Adj. Close'] * 100

/Users/mbbssnw3/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
df['PCT_Change'] = (df['Adj. High']-df['Adj. Open'])/df['Adj. Open']*100

/Users/mbbssnw3/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
df = df[['Adj. Close','HL_PCT','PCT_Change','Adj. Volume']]

In [33]:
df.head()

            Adj. Close    HL_PCT  PCT_Change  Adj. Volume
Date
2004-08-19   50.322842  3.712563    4.049595   44659000.0
2004-08-20   54.322689  0.710922    7.989308   22834300.0
2004-08-23   54.869377  3.729433    2.455760   18256100.0
2004-08-24   52.597363  6.417469    0.323625   15247300.0
2004-08-25   53.164113  1.886792    3.092784    9188600.0

In [34]:
forecast_col = 'Adj. Close'

In [35]:
df.fillna(-99999, inplace=True)

In [36]:
forecast_out = int(math.ceil(0.01*len(df)))

This below shifts the adjusted close price 10 days on

In [37]:
df['label'] = df[forecast_col].shift(-forecast_out)

In [38]:
df.head()

            Adj. Close    HL_PCT  PCT_Change  Adj. Volume      label
Date
2004-08-19   50.322842  3.712563    4.049595   44659000.0  69.639972
2004-08-20   54.322689  0.710922    7.989308   22834300.0  69.078238
2004-08-23   54.869377  3.729433    2.455760   18256100.0  67.839414
2004-08-24   52.597363  6.417469    0.323625   15247300.0  68.912727
2004-08-25   53.164113  1.886792    3.092784    9188600.0  70.668146

In [26]:
df.dropna(inplace=True)
df.drop(['label'],1)

ValueError: labels ['label'] not contained in axis

In [25]:
X = np.array(df.drop(['label'],1))
y = np.array(df['label'])

ValueError: labels ['label'] not contained in axis